### ISSUE TITLE
Causing "source: not found" issue

### ISSUE THREAD

**Issue by ronniesong0809** [DavidWhitlock/PortlandStateJavaGettingStarted#3]
https://github.com/DavidWhitlock/PortlandStateJavaGettingStarted/blob/d6811126f2ef2a32eff0ba04db5c2a25200d538a/createProject0.sh#L1

![image](https://user-images.githubusercontent.com/6004123/60234384-e51df300-9858-11e9-9f0b-4d0ed82ff107.png)

**Comment by DavidWhitlock** [comment]
A couple of students who were all running Ubuntu Linux noticed this problem last night.  It appears to be caused by the fact that `/bin/sh` does not map to `bash` on Ubuntu.

https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell

So, I'll just replace `/bin/sh` with `/bin/bash`, I guess.

**Comment by DavidWhitlock** [comment]
What do think @ronniesong0809?  Are there other changes that you'd like to see related to this issue?

**Comment by ronniesong0809** [comment]
> What do think @ronniesong0809? Are there other changes that you'd like to see related to this issue?

It perfectly solves the problem, I have no further comments.
